name: Welcome New Contributor

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening your first issue. It's great having you contribute to this project"
          pr-message: "Congrats for making your first pull request and thanks for taking the time to improve the product. It's great having you contribute to this project"
